[openai]
api_key = "YOUR_API_KEY"
#model = text-davinci-003
#model = gpt-3.5-turbo-instruct
model = gpt-4o-mini
retry_delay = 1
max_retries = 3

[extractor]
file_folder = sample_forms
results_folder = run_results
metrics_folder = run_metrics
parser_config = closewise_parser_configurator.json

[prompt_eng]
prefix = Extract the values of the following fields from the closing confirmation text:
midfix = Text:
suffix = Do not change the name of the fields.
max_chunk = 2000
splits = 2
max_tokens = 7500
response_tokens = 16000
prompt_threshold = 200
stopwords = stopwords.txt